app:
  version: ${APP_VERSION:local}
  name: springlab-Alan-herrera

server:
  port: ${PORT:8080}

spring:
  #Configuracion del datasource
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}

  #Configuracion de H2 Console (solo para desarrollo/demo)
  h2:
    console:
      enabled: true
      path: /h2-console

  #Configuracion de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  #Configuracion de Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false

  #Configurar DevTools
  devtools:
    restart:
      enabled: true