app:
  version: ${APP_VERSION:local}
  name: springlab-Alan-herrera

server:
  port: ${PORT:8080}

spring:
  #Configuracion del datasource
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/spring_lab?useSSL=false&serverTimezone=UTC}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  #Configuracion de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  #Configuracion de Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false

  #Configurar DevTools
  devtools:
    restart:
      enabled: true